import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "../../../src/components/site/Breadcrumbs";
import { ClinicProviderCard, DoctorServiceCard, formatPublicServicePrice } from "../../../src/components/site/Cards";
import { Container } from "../../../src/components/site/Container";
import { Section } from "../../../src/components/site/Section";
import { SiteLayout } from "../../../src/components/site/SiteLayout";
import { pageMetadata } from "../../../src/lib/metadata";
import { publicCatalogService, publicDoctors } from "../../../src/lib/public-api-server";
type Props = { params: Promise<{ serviceExposureId: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { serviceExposureId: slug } = await params; const result = await publicCatalogService(slug); return pageMetadata(result?.service.name ?? "Service", "Find doctors and clinics offering this service at The CliniQ.", `/services/${encodeURIComponent(slug)}`); }
export default async function ServiceDetailPage({ params }: Props) { const { serviceExposureId: slug } = await params; const result = await publicCatalogService(slug); if (!result) notFound(); const [doctorProfiles] = await Promise.all([publicDoctors()]); const doctorsBySlug = new Map(doctorProfiles.map((doctor) => [doctor.slug, doctor])); const { service, doctors, clinics } = result; const providerCounts = [service.doctorCount ? `${service.doctorCount} ${service.doctorCount === 1 ? "doctor" : "doctors"}` : null, service.clinicCount ? `${service.clinicCount} ${service.clinicCount === 1 ? "clinic" : "clinics"}` : null].filter(Boolean).join(" · "); return <SiteLayout><Section tint><Container><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Services", href: "/services" }, { label: service.name }]} /><p className="eyebrow">Healthcare service</p><h1 className="section-heading">{service.name}</h1><p className="section-copy">{service.description ?? "Find doctors and clinics offering this service."}</p>{service.startingPrice || providerCounts ? <div className="service-card-details">{service.startingPrice ? <span className="service-card-price">Starts from {formatPublicServicePrice(service.startingPrice)}</span> : null}{providerCounts ? <span className="service-card-meta">{providerCounts}</span> : null}</div> : null}</Container></Section><Section><Container><p className="eyebrow">Available doctors</p><h2 className="section-heading">Doctors offering {service.name}</h2>{doctors.length ? <div className="grid grid--three">{doctors.map((provider) => <DoctorServiceCard key={provider.serviceExposureId} provider={provider} serviceName={service.name} doctor={doctorsBySlug.get(provider.slug)} />)}</div> : <p className="directory-empty">No doctors are currently available for this service.</p>}</Container></Section><Section tint><Container><p className="eyebrow">Available clinics</p><h2 className="section-heading">Clinics offering {service.name}</h2>{clinics.length ? <div className="grid grid--three">{clinics.map((provider) => <ClinicProviderCard key={provider.serviceExposureId} provider={provider} serviceName={service.name} />)}</div> : <p className="directory-empty">No clinics are currently available for this service.</p>}</Container></Section></SiteLayout>; }
