import type { PublicCatalogProvider, PublicCatalogService, PublicClinic, PublicClinicReference, PublicClinicServiceDoctorAssignment, PublicDoctor, PublicDoctorReference, PublicPresentation, PublicProfileService, PublicService } from "./api";
const base = (process.env.PLATFORM_API_BASE_URL ?? process.env.NEXT_PUBLIC_PLATFORM_API_BASE_URL ?? "").replace(/\/$/, "");
async function read<T>(path: string, fresh = false): Promise<T | null> { if (!base) return null; try { const response = await fetch(`${base}${path}`, fresh ? { cache: "no-store" } : { next: { revalidate: 60 } }); return response.ok ? await response.json() as T : null; } catch { return null; } }
export async function publicDoctors(query?: string): Promise<PublicDoctor[]> { return (await read<{ items: PublicDoctor[] }>(`/v1/public/doctors${query ? `?q=${encodeURIComponent(query)}` : ""}`))?.items ?? []; }
export async function publicDoctor(slug: string): Promise<{ doctor: Omit<PublicDoctor, "id">; presentation: PublicPresentation; services: PublicProfileService[]; clinics: PublicClinicReference[] } | null> { return read(`/v1/public/doctors/${encodeURIComponent(slug)}`, true); }
export async function publicClinics(query?: string): Promise<PublicClinic[]> { return (await read<{ items: PublicClinic[] }>(`/v1/public/clinics${query ? `?q=${encodeURIComponent(query)}` : ""}`))?.items ?? []; }
export async function publicClinic(slug: string): Promise<{ clinic: Omit<PublicClinic, "id">; presentation: PublicPresentation; services: PublicProfileService[]; doctors: PublicDoctorReference[] } | null> { return read(`/v1/public/clinics/${encodeURIComponent(slug)}`, true); }
export async function publicServices(query?: string): Promise<PublicService[]> { return (await read<{ items: PublicService[] }>(`/v1/public/service-exposures${query ? `?q=${encodeURIComponent(query)}` : ""}`))?.items ?? []; }
export async function publicService(id: string): Promise<PublicService | null> { return (await publicServices()).find((service) => service.id === id) ?? null; }
export async function publicEligibleDoctors(exposureId: string): Promise<PublicClinicServiceDoctorAssignment[]> { return await read<PublicClinicServiceDoctorAssignment[]>(`/v1/public/service-exposures/${encodeURIComponent(exposureId)}/eligible-doctors`, true) ?? []; }
export async function publicCatalogServices(query?: string): Promise<PublicCatalogService[]> { return (await read<{ items: PublicCatalogService[] }>(`/v1/public/services${query ? `?q=${encodeURIComponent(query)}` : ""}`))?.items ?? []; }
export async function publicCatalogService(slug: string): Promise<{ service: PublicCatalogService; doctors: PublicCatalogProvider[]; clinics: PublicCatalogProvider[] } | null> { return read(`/v1/public/services/${encodeURIComponent(slug)}`); }
