import { CatalogServiceCard } from "../../src/components/site/Cards";
import { directoryPage, DirectoryPagination, pagedItems } from "../../src/components/site/DirectoryPagination";
import { Container } from "../../src/components/site/Container";
import { PageHero } from "../../src/components/site/PageHero";
import { Section } from "../../src/components/site/Section";
import { SiteLayout } from "../../src/components/site/SiteLayout";
import { pageMetadata } from "../../src/lib/metadata";
import { publicCatalogServices } from "../../src/lib/public-api-server";
export const metadata = pageMetadata("Services", "Find healthcare services and available appointments at The CliniQ.", "/services");
export default async function ServicesPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) { const { q, page: pageValue } = await searchParams; const services = await publicCatalogServices(q); const page = directoryPage(pageValue); const listing = pagedItems(services, page); return <SiteLayout><PageHero eyebrow="Consultation discovery" title="Find the right care for you" description="Choose a healthcare service to find doctors and clinics offering it." /><Section><Container><div className="directory-toolbar"><div><p className="eyebrow">Popular services</p><h2 className="section-heading">Choose a service to continue.</h2></div><form className="search-form"><label className="field"><span className="sr-only">Search services</span><input className="input" name="q" defaultValue={q} placeholder="Search services" /></label><button className="button">Search</button></form></div>{services.length ? <><p className="directory-result-count">{services.length} {services.length === 1 ? "service" : "services"} available</p><div className="grid grid--three">{listing.items.map((service) => <CatalogServiceCard service={service} key={service.id} />)}</div><DirectoryPagination pathname="/services" query={q} page={listing.currentPage} total={services.length} pageSize={listing.pageSize} /></> : <p className="directory-empty">No governed services are available for public discovery right now.</p>}</Container></Section></SiteLayout>; }
