import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "../../../src/components/site/Breadcrumbs";
import { ClinicReferenceCard, ServiceCard } from "../../../src/components/site/Cards";
import { JsonLd } from "../../../src/components/site/JsonLd";
import { SiteLayout } from "../../../src/components/site/SiteLayout";
import { pageMetadata, siteUrlValue } from "../../../src/lib/metadata";
import { publicDoctor } from "../../../src/lib/public-api-server";
import { PublicProfilePresentation } from "../../../src/components/site/PublicProfilePresentation";
import { ProfileCardList } from "../../../src/components/site/ProfileCardList";
type Props = { params: Promise<{ doctorProfileId: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { doctorProfileId: slug } = await params; const data = await publicDoctor(slug); const name = data?.doctor.displayName ?? "Doctor profile"; const specialty = data?.doctor.specialties[0]; return pageMetadata(name, specialty ? `${name} — ${specialty}. View currently published services at The CliniQ.` : `View currently published services for ${name} at The CliniQ.`, `/doctors/${encodeURIComponent(slug)}`); }
export default async function DoctorDetailPage({ params }: Props) { const { doctorProfileId: slug } = await params; const data = await publicDoctor(slug); if (!data) notFound(); const d=data.doctor,label=d.displayName??"Doctor profile",details=[d.biography||d.yearsExperience?{key:"about",title:"About",group:"details" as const,content:<>{d.biography?<p className="section-copy">{d.biography}</p>:null}{d.yearsExperience?<p>{d.yearsExperience} years of experience</p>:null}</>}:null,d.qualifications?.length?{key:"qualifications",title:"Qualifications",group:"details" as const,content:<div className="profile-list">{d.qualifications.map(x=><p key={`${x.credential}-${x.institution}`}>{x.credential} · {x.institution}{x.completionYear?` (${x.completionYear})`:""}</p>)}</div>}:null,d.languages?.length?{key:"languages",title:"Languages",group:"details" as const,content:<p>{d.languages.join(" · ")}</p>}:null].filter((section): section is NonNullable<typeof section> => section!==null); return <SiteLayout><Breadcrumbs inContainer items={[{label:"Home",href:"/"},{label:"Doctors",href:"/doctors"},{label}]}/><PublicProfilePresentation kind="Doctor" name={label} subtitle={[d.professionalTitle,...d.specialties].filter(Boolean).join(" · ")} summary={d.shortIntroduction} photo={d.photo} presentation={data.presentation} bookingHref={data.services.length?`/book/doctors/${encodeURIComponent(slug)}`:undefined} shareHref={`/doctors/${encodeURIComponent(slug)}`} sections={[...details,{key:"services",title:"Services",content:data.services.length?<ProfileCardList itemLabel="service">{data.services.map(x=><ServiceCard key={x.id} service={x} href={`/services/offering/${encodeURIComponent(x.id)}?doctor=${encodeURIComponent(slug)}`}/>)}</ProfileCardList>:<p>No services are currently listed.</p>},{key:"clinics",title:"Clinics",tint:true,content:data.clinics.length?<ProfileCardList itemLabel="clinic">{data.clinics.map(x=><ClinicReferenceCard key={x.slug} clinic={x}/>)}</ProfileCardList>:<p>No clinics are currently listed.</p>}]}/><JsonLd value={{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:siteUrlValue},{"@type":"ListItem",position:2,name:"Doctors",item:`${siteUrlValue}/doctors`},{"@type":"ListItem",position:3,name:label}]}}/></SiteLayout>; }
