import { DoctorCard } from "../../src/components/site/Cards";
import { directoryPage, DirectoryPagination, pagedItems } from "../../src/components/site/DirectoryPagination";
import { Container } from "../../src/components/site/Container";
import { PageHero } from "../../src/components/site/PageHero";
import { Section } from "../../src/components/site/Section";
import { SiteLayout } from "../../src/components/site/SiteLayout";
import { pageMetadata } from "../../src/lib/metadata";
import { publicDoctors } from "../../src/lib/public-api-server";
export const metadata = pageMetadata("Doctors", "Explore currently available public doctor profiles at The CliniQ.", "/doctors");
export default async function DoctorsPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) { const { q, page: pageValue } = await searchParams; const doctors = await publicDoctors(q); const listing = pagedItems(doctors, directoryPage(pageValue)); return <SiteLayout><PageHero eyebrow="Public directory" title="Explore doctors" description="Browse currently published doctor profiles and their available public services." /><Section><Container><div className="directory-toolbar"><div><p className="eyebrow">Available profiles</p><h2 className="section-heading">Find the right starting point.</h2></div><form className="search-form"><label className="field"><span className="muted">Search by name</span><input className="input" name="q" defaultValue={q} /></label><button className="button">Search</button></form></div>{doctors.length ? <><p className="directory-result-count">{doctors.length} {doctors.length === 1 ? "doctor" : "doctors"} available</p><div className="grid grid--three">{listing.items.map((doctor) => <DoctorCard doctor={doctor} key={doctor.id} />)}</div><DirectoryPagination pathname="/doctors" query={q} page={listing.currentPage} total={doctors.length} pageSize={listing.pageSize} /></> : <p className="directory-empty">No public doctor profiles are available right now. Published profiles will appear here when available.</p>}</Container></Section></SiteLayout>; }
