import Link from "next/link";
import type { CSSProperties, ReactNode } from "react";
import type { PublicPresentation } from "../../lib/api";
import { publicPresentation } from "../../lib/public-presentation";
export { weekdayLabel } from "../../lib/public-profile-format";
import { Container } from "./Container";
import { ProfileSummary } from "./ProfileSummary";
import { Section } from "./Section";
import { ShareButton } from "./ShareButton";

type ProfileSection={key:string;title:string;content:ReactNode;tint?:boolean;group?:"details"};
type Props={kind:"Doctor"|"Clinic";name:string;subtitle?:string|null;summary?:string|null;photo?:{url:string}|null;presentation:PublicPresentation;bookingHref?:string;shareHref?:string;bookingTarget?:"_self"|"_top";mode?:"full-page"|"embed";sections:ProfileSection[]};
export function PublicProfilePresentation({kind,name,subtitle,summary,photo,presentation,bookingHref,shareHref,bookingTarget="_self",mode="full-page",sections}:Props){const value=publicPresentation(presentation),hero=value.assets.find(asset=>asset.kind==="HERO_IMAGE"),background=value.assets.find(asset=>asset.kind==="BACKGROUND_IMAGE"),logo=value.assets.find(asset=>asset.kind==="LOGO"),centered=value.layoutOptions.heroLayout==="centered",visible=sections.filter(section=>value.sectionVisibility[section.key]!==false),details=visible.filter(section=>section.group==="details"),standard=visible.filter(section=>section.group!=="details"),profileImage=photo?.url||"/brand/consultation.png",style={"--presentation-primary":value.primaryColor??"#14345e","--presentation-accent":value.accentColor??"#13796b","--presentation-surface":value.secondaryColor??"#edf5f3"} as CSSProperties;return <main className={`public-presentation presentation-mode-${mode} template-${value.templateKey}${centered?" layout-centered":""}`} style={style}>{background?<img className="presentation-background" src={background.url} alt=""/>:null}<Section tint><Container><div className={`public-presentation-hero${hero?" presentation-has-hero-image":""}`}>{hero?<img className="presentation-hero-image" src={hero.url} alt=""/>:null}{logo?<img className="presentation-logo" src={logo.url} alt=""/>:null}<div className="profile-hero"><img className={`profile-photo${photo?.url?"":" profile-photo--default"}`} src={profileImage} alt={photo?.url?`${name} profile photo`:"The CliniQ default profile image"}/><div className="profile-hero-content"><p className="eyebrow">{kind} profile</p><h1 className="section-heading">{name}</h1>{subtitle?<p className="section-copy profile-subtitle">{subtitle}</p>:null}{summary?<ProfileSummary>{summary}</ProfileSummary>:null}<div className="profile-actions">{bookingHref?<Link className="button" href={bookingHref} target={bookingTarget}>Book appointment</Link>:null}{shareHref&&mode==="full-page"?<ShareButton href={shareHref} title={`${name} | The CliniQ`}/>:null}</div></div></div></div></Container></Section>{details.length?<Section><Container><div className="profile-detail-grid">{details.map(section=><article className="profile-detail-card" key={section.key}><h2 className="section-heading">{section.title}</h2>{section.content}</article>)}</div></Container></Section>:null}{standard.map(section=><Section key={section.key} tint={section.tint}><Container><h2 className="section-heading">{section.title}</h2>{section.content}</Container></Section>)}</main>}
